name: Build (Windows)

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (CMake, Ninja)
        run: |
          choco install -y cmake ninja

      - name: Set up Qt (MSVC 2019)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.1'
          arch: win64_msvc2019_64
          modules: 'qtbase qttools'

      - name: Check compiler and tools
        run: |
          cl.exe
          cmake --version
          ninja --version

      - name: Configure CMake (MSVC + Ninja)
        run: |
          cmake -S . -B build -G "Ninja Multi-Config"

      - name: Build Release
        run: cmake --build build --config Release --parallel

      - name: List build output
        run: dir build\Release
