name: Build (Windows)

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-windows-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Set up Qt (MSVC 2019)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.3'
          arch: win64_msvc2019_64

      - name: Check CMake and Ninja
        run: |
          cmake --version
          ninja --version

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install OpenAL and libsndfile (vcpkg)
        run: |
          .\vcpkg\vcpkg.exe install openal-soft:x64-windows libsndfile:x64-windows

      - name: Configure CMake (Visual Studio)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build Release
        run: cmake --build build --config Release --parallel

      - name: List build output
        run: dir build\Release
